const navData = [
	{
		id: 1,
		title: "Home",
		links: [],
	},
	{
		id: 2,
		title: "About",
		links: [],
	},
	{
		id: 3,
		title: "Our Team",
		links: [],
	},
	{
		id: 4,
		title: "Join Us",
		links: [
			{ label: "Instructor", url: "/join" },
			{ label: " Data Science & Analysis", url: "/join" },
			{ label: "Product Manager", url: "/join" },
			{ label: "Research", url: "/join" },
			{ label: "Backend", url: "/join" },
			{ label: "Frontend", url: "/join" },
			{ label: "Artificial Intelligence", url: "/join" },
			{ label: "Web Development", url: "/join" },
			{ label: "App Development", url: "/join" },
			{ label: "Aircraft Designs", url: "/join" },
			{ label: "3D Modelling", url: "/join" },
			{ label: "Software Development", url: "/join" },
			{ label: " Product Engineers (coming soon)", url: "/join" },
			{ label: "Customer Service", url: "/join" },
		],
	},
	{
		id: 5,
		title: "Services",
		links: [],
	},
	{
		id: 6,
		title: "Research",
		links: [
			{ label: "Aerodynamics", url: "/research" },
			{ label: "Fluid mechanics", url: "/research" },
			{ label: "Avionics", url: "/research" },
			{ label: "Flight dynamics", url: "/research" },
			{ label: "Thermodynamics", url: "/research" },
			{ label: "Engineering physics", url: "/research" },
			{ label: "Materials Science", url: "/research" },
			{ label: "Aircraft Structures", url: "/research" },
			{ label: "Mechanics", url: "/research" },
			{ label: "Chemical engineering", url: "/research" },
			{ label: "Applied mechanics", url: "/research" },
			{ label: "Dynamics", url: "/research" },
			{ label: "Aircraft flight mechanics", url: "/research" },
			{ label: "Control system", url: "/research" },
			{ label: "Solid mechanics", url: "/research" },
			{ label: "strength of materials", url: "/research" },
			{ label: "computational fluid dynamics", url: "/research" },
			{ label: "Numerical analysis", url: "/research" },
			{ label: "Stress", url: "/research" },
			{ label: "Control engineering", url: "/research" },
			{ label: "Structural mechanics", url: "/research" },
		],
	},
	{
		id: 7,
		title: "Education",
		links: [],
	},
	{
		id: 8,
		title: "Contact",
		links: [],
	},
];

export default navData;
